param(
    [Parameter(Mandatory = $true)]
    [string]$CsvPath,

    [Parameter(Mandatory = $true)]
    [string]$Email,

    [string]$OutFile = "tmp/history-import.sql"
)

$ErrorActionPreference = "Stop"

function SqlString([string]$Value) {
    if ([string]::IsNullOrWhiteSpace($Value)) {
        return "NULL"
    }
    return "'" + $Value.Replace("'", "''") + "'"
}

function SqlDate([string]$Value) {
    if ([string]::IsNullOrWhiteSpace($Value)) {
        return "NULL"
    }
    if ($Value -match "(\d{4}).*?(\d{1,2}).*?(\d{1,2})") {
        $dateValue = "{0:D4}-{1:D2}-{2:D2}" -f [int]$matches[1], [int]$matches[2], [int]$matches[3]
        return SqlString $dateValue
    }
    return "NULL"
}

function PeriodKey([string]$Value) {
    if ($Value -match "(\d{4}).*?(\d{1,2})") {
        $year = [int]$matches[1]
        $month = [int]$matches[2]
        $half = if ($month -le 6) { "H1" } else { "H2" }
        return [pscustomobject]@{
            Key = "$year-$half"
            Year = $year
            Half = $half
        }
    }
    return [pscustomobject]@{
        Key = "UNKNOWN"
        Year = "NULL"
        Half = "UNKNOWN"
    }
}

function K([int[]]$Codepoints) {
    return -join ($Codepoints | ForEach-Object { [char]$_ })
}

function HasText([string]$Value, [int[]]$Codepoints) {
    return $Value.Contains((K $Codepoints))
}

function ResultStage([string]$Value) {
    if (HasText $Value @(0xC9C4, 0xD589)) { return "IN_PROGRESS" }
    if (HasText $Value @(0xBA74, 0xC811)) { return "INTERVIEW_FAILED" }
    if ((HasText $Value @(0xD544, 0xAE30)) -or (HasText $Value @(0xC5ED, 0xB7C9)) -or (HasText $Value @(0xAC80, 0xC0AC)) -or (HasText $Value @(0xACFC, 0xC81C))) {
        return "TEST_FAILED"
    }
    if (HasText $Value @(0xC11C, 0xB958)) { return "DOCUMENT_FAILED" }
    return "NOT_APPLIED"
}

function ResultLabel([string]$Stage) {
    switch ($Stage) {
        "IN_PROGRESS" { "In progress" }
        "INTERVIEW_FAILED" { "Interview stage ended" }
        "TEST_FAILED" { "Test/assignment stage ended" }
        "DOCUMENT_FAILED" { "Document stage ended" }
        default { "Not applied" }
    }
}

function ApplicationStatus([string]$Stage) {
    if ($Stage -eq "IN_PROGRESS") {
        return "IN_PROGRESS"
    }
    return "NOT_APPLIED"
}

function CompanyType([string]$CompanyName, [string]$SourceUrl) {
    $domainHost = DomainFromUrl $SourceUrl
    if ($domainHost -match "bank|finance|kdb|shinhan|kb|woori|hana|nh|ibk|samsunglife|hanwhalife") {
        return "Finance/Public"
    }
    if ($domainHost -match "samsung|hyundai|lg|sk|naver|kakao|nexon|hanwha|cj|kt|nhn|coupang|linecorp|woowahan|toss|lotte|koreanair") {
        return "Enterprise"
    }
    if ($domainHost -match "dalpha|wrtn|upstage|wanted|buzzvil|classum|channel") {
        return "Startup"
    }
    if ((HasText $CompanyName @(0xC740, 0xD589)) -or (HasText $CompanyName @(0xBCF4, 0xD5D8)) -or (HasText $CompanyName @(0xC99D, 0xAD8C)) -or (HasText $CompanyName @(0xAE08, 0xC735))) {
        return "Finance/Public"
    }
    return "Other"
}

function DomainFromUrl([string]$Url) {
    if ([string]::IsNullOrWhiteSpace($Url)) {
        return $null
    }
    try {
        return ([Uri]$Url).Host
    } catch {
        return $null
    }
}

function FieldByIndex($Row, [int]$Index) {
    $properties = @($Row.PSObject.Properties)
    if ($properties.Count -le $Index -or $null -eq $properties[$Index].Value) {
        return ""
    }
    return [string]$properties[$Index].Value
}

if (!(Test-Path -LiteralPath $CsvPath)) {
    throw "CSV file not found: $CsvPath"
}

$rows = Import-Csv -LiteralPath $CsvPath
$outDir = Split-Path -Parent $OutFile
if (![string]::IsNullOrWhiteSpace($outDir) -and !(Test-Path -LiteralPath $outDir)) {
    New-Item -ItemType Directory -Path $outDir | Out-Null
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("-- Generated by tools/import-history-csv.ps1")
$lines.Add("-- Review this SQL before running it against a database.")
$lines.Add("START TRANSACTION;")
$lines.Add("SET @history_user_email = $(SqlString $Email);")
$lines.Add("SELECT @history_user_id := id FROM users WHERE email = @history_user_email LIMIT 1;")
$lines.Add("")

$index = 0
foreach ($row in $rows) {
    $index += 1
    $companyName = (FieldByIndex $row 0).Trim()
    $sourceUrl = (FieldByIndex $row 1).Trim()
    $rawResult = (FieldByIndex $row 2).Trim()
    $deadlineLabel = (FieldByIndex $row 3).Trim()
    $positionTitle = (FieldByIndex $row 4).Trim()
    if ([string]::IsNullOrWhiteSpace($companyName) -or [string]::IsNullOrWhiteSpace($positionTitle)) {
        continue
    }

    $stage = ResultStage $rawResult
    $status = ApplicationStatus $stage
    $period = PeriodKey $deadlineLabel
    $deadlineDate = SqlDate $deadlineLabel
    $companyType = CompanyType $companyName $sourceUrl
    $domain = DomainFromUrl $sourceUrl
    $resultLabel = ResultLabel $stage
    $fallbackDeadlineLabel = if ([string]::IsNullOrWhiteSpace($deadlineLabel)) { "No deadline" } else { $deadlineLabel }

    $lines.Add("-- Row ${index}: $companyName / $positionTitle")
    $lines.Add("INSERT INTO companies (name, domain, company_type, size)")
    $lines.Add("VALUES ($(SqlString $companyName), $(SqlString $domain), $(SqlString $companyType), 'Unknown')")
    $lines.Add("ON DUPLICATE KEY UPDATE domain = COALESCE(domain, VALUES(domain)), company_type = COALESCE(company_type, VALUES(company_type)), updated_at = CURRENT_TIMESTAMP;")
    $lines.Add("SELECT @history_company_id := id FROM companies WHERE name = $(SqlString $companyName) LIMIT 1;")
    $lines.Add("INSERT INTO jobs (company_id, title, role, deadline_label, deadline_at, source, url)")
    $lines.Add("SELECT @history_company_id, $(SqlString $positionTitle), $(SqlString $positionTitle), $(SqlString $fallbackDeadlineLabel), $deadlineDate, 'HISTORY_IMPORT', $(SqlString $sourceUrl)")
    $lines.Add("WHERE NOT EXISTS (SELECT 1 FROM jobs WHERE company_id = @history_company_id AND title = $(SqlString $positionTitle) AND url = $(SqlString $sourceUrl));")
    $lines.Add("SELECT @history_job_id := id FROM jobs WHERE company_id = @history_company_id AND title = $(SqlString $positionTitle) AND url = $(SqlString $sourceUrl) ORDER BY id DESC LIMIT 1;")
    $lines.Add("INSERT INTO basket_jobs (user_id, job_id, application_status, status_reason, saved_source)")
    $lines.Add("SELECT @history_user_id, @history_job_id, '$status', '$stage', 'HISTORY_IMPORT'")
    $lines.Add("WHERE @history_user_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM basket_jobs WHERE user_id = @history_user_id AND job_id = @history_job_id AND deleted_at IS NULL);")
    $lines.Add("SELECT @history_basket_job_id := id FROM basket_jobs WHERE user_id = @history_user_id AND job_id = @history_job_id AND deleted_at IS NULL ORDER BY id DESC LIMIT 1;")
    $lines.Add("INSERT INTO workspaces (user_id, basket_job_id)")
    $lines.Add("SELECT @history_user_id, @history_basket_job_id")
    $lines.Add("WHERE @history_user_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM workspaces WHERE basket_job_id = @history_basket_job_id);")
    $lines.Add("SELECT @history_workspace_id := id FROM workspaces WHERE basket_job_id = @history_basket_job_id LIMIT 1;")
    $lines.Add("INSERT INTO application_history (user_id, workspace_id, company_name, position_title, application_status, result_stage, result_label, raw_result, deadline_label, deadline_date, period_key, period_year, period_half, source_url, company_type)")
    $lines.Add("SELECT @history_user_id, @history_workspace_id, $(SqlString $companyName), $(SqlString $positionTitle), '$status', '$stage', $(SqlString $resultLabel), $(SqlString $rawResult), $(SqlString $fallbackDeadlineLabel), $deadlineDate, $(SqlString $period.Key), $($period.Year), $(SqlString $period.Half), $(SqlString $sourceUrl), $(SqlString $companyType)")
    $lines.Add("WHERE @history_user_id IS NOT NULL AND @history_workspace_id IS NOT NULL")
    $lines.Add("ON DUPLICATE KEY UPDATE application_status = VALUES(application_status), result_stage = VALUES(result_stage), result_label = VALUES(result_label), raw_result = VALUES(raw_result), updated_at = CURRENT_TIMESTAMP;")
    $lines.Add("")
}

$lines.Add("COMMIT;")
$lines | Set-Content -LiteralPath $OutFile -Encoding UTF8
Write-Host "Wrote $($rows.Count) source rows to $OutFile"
